/*
Post-Deployment Script Template                            
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.        
 Use SQLCMD syntax to include a file in the post-deployment script.            
 Example:      :r .\myfile.sql                                
 Use SQLCMD syntax to reference a variable in the post-deployment script.        
 Example:      :setvar TableName MyTable                            
               SELECT * FROM [$(TableName)]                    
--------------------------------------------------------------------------------------
*/

-- Birth cards
INSERT INTO [cards].[BirthCards] ([name], [type], [color], [expansion], [effects], [iconinfoif])
VALUES
    ('The Birth of Life', 1, 0, 1, 1, NULL);

-- Gene Pool cards
INSERT INTO [cards].[GenePoolCards] ([name], [type], [color], [expansion], [effects], [iconinfoid])
VALUES
    ('unnamed', 4, 256, 1, 10, NULL);

-- Player Aid cards
INSERT INTO [cards].[PlayerAidCards] ([name], [type], [color], [expansion], [effects], [iconinfoid])
VALUES
    ('Player Aids', 5, 256, 1, 0, NULL);

-- Age cards
INSERT INTO [cards].[AgeCards] ([name], [type], [color], [expansion], [effects], [iconinfoid])
VALUES
    ('Age of Peace', 2, 0, 1, 2, NULL),
    ('Age of Dracula', 2, 0, 1, 2, NULL),
    ('Age of Nietzsche', 2, 0, 1, 2, NULL),
    ('Age of Reason', 2, 0, 1, 2, NULL),
    ('Age of Wonder', 2, 0, 1, 2, NULL),
    ('Alien Terraform', 2, 0, 1, 2, NULL),
    ('Arid Lands', 2, 0, 1, 2, NULL),
    ('Atmospheric Thickening', 2, 0, 1, 2, NULL),
    ('Awakening', 2, 0, 1, 2, NULL),
    ('Birth of a Hero', 2, 0, 1, 2, NULL),
    ('Coastal Formations', 2, 0, 1, 2, NULL),
    ('Comet Showers', 2, 0, 1, 2, NULL),
    ('Eclipse', 2, 0, 1, 2, NULL),
    ('Enlightenment', 2, 0, 1, 2, NULL),
    ('Flourish', 2, 0, 1, 2, NULL),
    ('Galactic Drift', 2, 0, 1, 2, NULL),
    ('Glacial Drift', 2, 0, 1, 2, NULL),
    ('High Tides', 2, 0, 1, 2, NULL),
    ('Joy', 2, 0, 2, 2, NULL),
    ('Lunar Retreat', 2, 0, 1, 2, NULL),
    ('Natural Harmony', 2, 0, 1, 2, NULL),
    ('Northern Winds', 2, 0, 1, 2, NULL),
    ('Prosperiety', 2, 0, 1, 2, NULL),
    ('Reforestation', 2, 0, 1, 2, NULL),
    ('Sea Kingdoms', 2, 0, 1, 2, NULL),
    ('Tectonic Shift', 2, 0, 1, 2, NULL),
    ('Temporal Sands', 2, 0, 1, 2, NULL),
    ('The Messiah', 2, 0, 1, 2, NULL),
    ('Tropical Lands', 2, 0, 1, 2, NULL),
    ('AI Takeover', 2, 0, 1, 3, NULL),
    ('Deus ex Machina', 2, 0, 1, 3, NULL),
    ('Glacial Meltdown', 2, 0, 1, 3, NULL),
    ('Grey Goo', 2, 0, 1, 3, NULL),
    ('Ice Age', 2, 0, 1, 3, NULL),
    ('Mass Extinction', 2, 0, 1, 3, NULL),
    ('Mega Tsunami', 2, 0, 1, 3, NULL),
    ('Nuclear Winter', 2, 0, 1, 3, NULL),
    ('Overpopulation', 2, 0, 1, 3, NULL),
    ('Pulse Event', 2, 0, 1, 3, NULL),
    ('Retrovirus', 2, 0, 1, 3, NULL),
    ('Solar Flare', 2, 0, 1, 3, NULL),
    ('Super Volcano', 2, 0, 1, 3, NULL),
    ('The Big One', 2, 0, 1, 3, NULL),
    ('The Four Horsemen', 2, 0, 1, 3, NULL),

    -- Dinolings
    ('Badlands', 2,	0, 5, 2, 'Dino egg'),
    ('Impact Event', 2, 0, 5, 3, 'Dino egg'),

    -- Mythlings
    ('Ozmorian Winds', 2, 0, 6, 2, 'Exotic Dragon'),
    ('Eyes Open from Behind the Stars', 2, 0, 6, 3, 'Exotic Dragon'),

    -- Techlings
    ('Age of Metadata', 2, 0, 7, 2, 'Cogs & Gears'),
    ('Bioengineered Plague', 2, 0, 7, 3, 'Cogs & Gears');

-- Sign cards
INSERT INTO [cards].[SignCards] ([name], [type], [color], [expansion], [effects], [icon])
VALUES
    ('The Bilbies', 6, 0, 8, 11, NULL),
    ('The Cabochan', 6, 0, 8, 11, NULL),
    ('The Cosmic Jinx', 6, 0, 8, 11, NULL),
    ('The Dancer', 6, 0, 8, 11, NULL),
    ('The Fellmonger', 6, 0, 8, 11, NULL),
    ('The Jellyfish', 6, 0, 8, 11, NULL),
    ('The Logician', 6, 0, 8, 11, NULL),
    ('The Lumberjack', 6, 0, 8, 11, NULL),
    ('The Magician', 6, 0, 8, 11, NULL),
    ('The Maven', 6, 0, 8, 11, NULL),
    ('The Soothsayer', 6, 0, 8, 11, NULL),
    ('The Spirit Gardener', 6, 0, 8, 11, NULL),
    ('The Tigris', 6, 0, 8, 11, NULL),
    ('The Vagrant', 6, 0, 8, 11, NULL),
    ('The Vixen', 6, 0, 8, 11, NULL),
    ('The Warbler', 6, 0, 8, 11, NULL),
    ('The Warrior', 6, 0, 8, 11, NULL),
    ('The Weaver', 6, 0, 8, 11, NULL);

-- Trait cards
INSERT INTO [cards].[TraitCards] ([name], [type], [color], [expansion], [effects], [icon])
VALUES
    ('Echolocation', 3, 1, 1, 4, 'Star'),
    ('Immunity', 3, 1, 1, 5, 'Star, Drop of Life'),
    ('Tiny', 3, 1, 1, 5, 'Star, Drop of Life'),
    ('Automimicry', 3, 1, 1, 6, 'A'),
    ('Blubber', 3, 1, 1, 0, NULL),
    ('Chromatophores', 3, 1, 1, 7, 'Wings!'),
    ('Cold Blood', 3, 1, 1, 6, 'A'),
    ('Costly Signaling', 3, 1, 1, 6, 'A'),
    ('Egg Clusters', 3, 1, 1, 5, 'Drop of Life'),
    ('Flight', 3, 1, 1, 6, 'A'),
    ('Gills', 3, 1, 1, 0, NULL),
    ('Iridescent Scales', 3, 1, 1, 6, 'A'),
    ('Migratory', 3, 1, 1, 0, NULL),
    ('Painted Shell', 3, 1, 1, 6, 'A'),
    ('Regenerative Tissue', 3, 1, 1, 4, NULL),
    ('Saliva', 3, 1, 1, 4, NULL),
    ('Selective Memory', 3, 1, 1, 6, 'A'),
    ('Spiny', 3, 1, 1, 0, NULL),
    ('Sweat', 3, 1, 1, 6, 'A'),
    ('Tentacles', 3, 1, 1, 6, 'A'),
    ('Scutes', 3, 1, 1, 6, 'A'),
    ('Tube Feet', 3, 1, 3, 6, 'A'),
    ('Heroic', 3, 2, 1, 4, 'Star'),
    ('Pack Behavior', 3, 2, 1, 5, 'Star, Drop of Life'),
    ('Symbiosis', 3, 2, 1, 5, 'Star, Drop of Life'),
    ('Appealing', 3, 2, 1, 0, NULL),
    ('Bark', 3, 2, 1, 0, NULL),
    ('Branches', 3, 2, 1, 5, 'Drop of Life'),
    ('Deep Roots', 3, 2, 1, 0, NULL),
    ('Fecundity', 3, 2, 1, 4, NULL),
    ('Fortunate', 3, 2, 1, 5, 'Drop of Life'),
    ('Leaves', 3, 2, 1, 0, NULL),
    ('Overgrowth', 3, 2, 1, 5, 'Drop of Life'),
    ('Photosynthesis', 3, 2, 1, 6, 'A'),
    ('Pollination', 3, 2, 1, 5, 'Drop of Life'),
    ('Propagation', 3, 2, 1, 6, 'A'),
    ('Random Fertilization', 3, 2, 1, 5, 'Drop of Life'),
    ('Self-Replicating', 3, 2, 1, 6, 'A'),
    ('Swarm', 3, 2, 1, 5, 'Drop of Life'),
    ('Tiny Little Melons', 3, 2, 1, 6, 'A'),
    ('Trunk', 3, 2, 1, 6, 'A'),
    ('Woody Stems', 3, 2, 1, 0, NULL),
    ('Beauty', 3, 2, 3, 6, 'A'),
    ('Denial', 3, 4, 1, 4, 'Star'),
    ('Faith', 3, 4, 1, 4, 'Star'),
    ('Optimistic Nihilism', 3, 4, 1, 4, 'Star'),
    ('Altruistic', 3, 4, 1, 5, 'Drop of Life'),
    ('Boredom', 3, 4, 1, 6, 'A'),
    ('Confusion', 3, 4, 1, 0, NULL),
    ('Delicious', 3, 4, 1, 4, NULL),
    ('Doting', 3, 4, 1, 6, 'A'),
    ('Eloquance', 3, 4, 1, 8, 'triangle'),
    ('Fear', 3, 4, 1, 0, NULL),
    ('Flatulence', 3, 4, 1, 0, NULL),
    ('Gratitude', 3, 4, 1, 5, 'Drop of Life'),
    ('Introspective', 3, 4, 1, 6, '"A"'),
    ('Just', 3, 4, 1, 4, NULL),
    ('Late', 3, 4, 1, 7, 'Wings!'),
    ('Mindful', 3, 4, 1, 5, 'Drop of Life'),
    ('Mitochondrion', 3, 4, 1, 4, NULL),
    ('Morality', 3, 4, 1, 4, NULL),
    ('Prepper', 3, 4, 1, 8, 'triangle'),
    ('Saudade', 3, 4, 1, 0, NULL),
    ('Self-Awareness', 3, 4, 1, 7, 'Wings!'),
    ('The Third Eye', 3, 4, 1, 6, '"A"'),
    ('Bones', 3, 4, 3, 6, '"A"'),
    ('Camouflage', 3, 8, 1, 5, 'Star, Drop of Life'),
    ('Vampirism', 3, 8, 1, 4, 'Star'),
    ('Viral', 3, 8, 1, 'World''s End; Scoring', 'Star; triangle; Drop of Life'),
    ('Adorable', 3, 8, 1, 0, NULL),
    ('Big Ears', 3, 8, 1, 0, NULL),
    ('Clever', 3, 8, 1, 6, '"A"'),
    ('Directly Register', 3, 8, 1, 6, '"A"'),
    ('Dreamer', 3, 8, 1, 4, NULL),
    ('Fine Motor Skills', 3, 8, 1, 0, NULL),
    ('Impatience', 3, 8, 1, 6, '"A"'),
    ('Inventive', 3, 8, 1, 6, '"A"'),
    ('Memory', 3, 8, 1, 6, '"A"'),
    ('Nocturnal', 3, 8, 1, 0, NULL),
    ('Nosy', 3, 8, 1, 6, '"A"'),
    ('Parasitic', 3, 8, 1, 7, 'Wings!'),
    ('Persuasive', 3, 8, 1, 6, '"A"'),
    ('Poisonous', 3, 8, 1, 6, '"A"'),
    ('Selfish', 3, 8, 1, 6, 'A'),
    ('Sneaky', 3, 8, 1, 'World''s End; Out of Turn Action', 'triangle; Wings!'),
    ('Sticky Secretions', 3, 8, 1, 5, 'Drop of Life'),
    ('Super Spreader', 3, 8, 1, 4, NULL),
    ('Teeth', 3, 8, 1, 4, NULL),
    ('Telekinetic', 3, 8, 1, 6, 'A'),
    ('Venomous', 3, 8, 1, 6, 'A'),
    ('Juicy', 3, 8, 3, 6, 'A'),
    ('Apex Predator', 3, 16, 1, 5, 'Star; Drop of Life'),
    ('Hyper-Inetelligence', 3, 16, 1, 8, 'Star; triangle'),
    ('Sentience', 3, 16, 1, 'World''s End; Scoring', 'Star; triangle; Drop of Life'),
    ('Antlers', 3, 16, 1, 0, NULL),
    ('Bad', 3, 16, 1, 6, 'A'),
    ('Brave', 3, 16, 1, 6, 'A'),
    ('Brute Strength', 3, 16, 1, 0, NULL),
    ('Endurance', 3, 16, 1, 4, NULL),
    ('Fangs', 3, 16, 1, 0, NULL),
    ('Fire Skin', 3, 16, 1, 0, NULL),
    ('Heat Vision', 3, 16, 1, 5, 'Drop of Life'),
    ('Hot Temper', 3, 16, 1, 6, 'A'),
    ('Kidney', 3, 16, 1, 5, 'Drop of Life'),
    ('Quick', 3, 16, 1, 0, NULL),
    ('Reckless', 3, 16, 1, 6, 'A'),
    ('Retractible Claws', 3, 16, 1, 4, NULL),
    ('Stone Skin', 3, 16, 1, 0, NULL),
    ('Territorial', 3, 16, 1, 6, 'A'),
    ('Voracious', 3, 16, 1, 6, 'A'),
    ('Warm Blood', 3, 16, 1, 4, NULL),
    ('Pride', 3, 16, 3, 6, 'A'),
    ('Fulfilled', 3, 32, 2, 4, NULL),
    ('Motley', 3, 64, 2, 4, 'Star'),
    ('Acrobatic', 3, 10, 4, 0, NULL),
    ('Bloom', 3, 3, 4, 0, NULL),
    ('Bullheaded', 3, 18, 4, 0, NULL),
    ('Curiosity', 3, 17, 4, 0, NULL),
    ('Hand-Wing', 3, 24, 4, 0, NULL),
    ('Mitosis', 3, 9, 4, 0, NULL),
    ('Free Will', 3, 4, 9, 8, 'triangle'),
    ('Tetrachromatic', 3, 8, 9, 5, 'Drop of Life'),

    -- Dinolings
    ('Elongated Neck', 3, 1, 5, 6, 'Dino egg; "A"'),
    ('Pterosaur Wings', 3, 1, 5, 6, 'Dino egg; "A"'),
    ('Terror Beak', 3, 1, 5, 4, 'Dino egg'),
    ('Bony Plates', 3, 2, 5, 6, 'Dino egg; "A"'),
    ('Ceratopsian Horns', 3, 2, 5, 0, 'Dino egg'),
    ('Fronds', 3, 2, 5, 4, 'Dino egg'),
    ('Thagomizer', 3, 2, 5, 6, 'Dino egg; "A"'),
    ('Cranial Crest', 3, 4, 5, 5, 'Dino egg; Drop of Life'),
    ('Dermal Armor', 3, 4, 5, 6, 'Dino egg; "A"'),
    ('Pycnofibers', 3, 4, 5, 6, 'Dino egg; "A"'),
    ('Egg Predation', 3, 8, 5, 6, 'Dino egg; "A"'),
    ('Protofeathers', 3, 8, 5, 6, 'Dino egg; "A"'),
    ('Talons', 3, 8, 5, 0, 'Dino egg'),
    ('Carnosaur Jaw', 3, 16, 5, 4, 'Dino egg; Star'),
    ('Serrated Teeth', 3, 16, 5, 5, 'Dino egg; Drop of Life'),
    ('Tiny Arms', 3, 16, 5, 5, 'Dino egg; Drop of Life'),

    -- Mythlings
    ('Legendary', 3, 1, 6, 4, 'Exotic Dragon; Star'),
    ('Diaphanous Wings', 3, 1, 6, 0, 'Exotic Dragon'),
    ('Icy', 3, 1, 6, 0, 'Exotic Dragon'),
    ('Righteous', 3, 1, 6, 7, 'Exotic Dragon; Wings!'),
    ('Elven Ears', 3, 2, 6, 5, 'Exotic Dragon; Drop of Life'),
    ('Fey', 3, 2, 6, 4, 'Exotic Dragon'),
    ('Orcish Tusks', 3, 2, 6, 6, 'Exotic Dragon; "A"'),
    ('Destined', 3, 4, 6, 0, 'Exotic Dragon'),
    ('Effigial', 3, 4, 6, 7, 'Exotic Dragon; Wings!'),
    ('Rainbow Horn', 3, 4, 6, 8, 'Exotic Dragon; triangle'),
    ('Necromantic', 3, 8, 6, 7, 'Exotic Dragon; Wings!'),
    ('Witchy', 3, 8, 6, 7, 'Exotic Dragon; Wings!'),
    ('Zombified', 3, 8, 6, 7, 'Exotic Dragon; Wings!'),
    ('Ancient', 3, 16, 6, 6, 'Exotic Dragon; "A"'),
    ('Dragon Heart', 3, 16, 6, 5, 'Exotic Dragon; Drop of Life'),
    ('Gelatinous', 3, 16, 6, 6, 'Exotic Dragon; "A"'),
    ('Mighty', 3, 16, 6, 6, 'Exotic Dragon; "A"'),

    -- Techlings
    ('Cybernetic', 3, 1, 7, 4, 'Cogs & Gears'),
    ('Mecha', 3, 1, 7, 6, 'Cogs & Gears; "A"'),
    ('Neural Link', 3, 1, 7, 6, 'Cogs & Gears; "A"'),
    ('Lyonization', 3, 2, 7, 4, 'Cogs & Gears'),
    ('Nano', 3, 2, 7, 5, 'Cogs & Gears; Drop of Life'),
    ('Transgenic Modification', 3, 2, 7, 4, 'Cogs & Gears'),
    ('Ruggedized', 3, 4, 7, 4, 'Cogs & Gears; Star'),
    ('Binary', 3, 4, 7, 6, 'Cogs & Gears; "A"'),
    ('GMO', 3, 4, 7, 5, 'Cogs & Gears; Drop of Life'),
    ('Grey Hat', 3, 4, 7, 6, 'Cogs & Gears; "A"'),
    ('Electromagnetic', 3, 8, 7, 6, 'Cogs & Gears; "A"'),
    ('Hypermyelination', 3, 8, 7, 5, 'Cogs & Gears; Drop of Life'),
    ('Subdermal Plating', 3, 8, 7, 7, 'Cogs & Gears; Wings!'),
    ('Bionic Arm', 3, 16, 7, 5, 'Cogs & Gears; Drop of Life'),
    ('Bone Reinforcement', 3, 16, 7, 0, 'Cogs & Gears'),
    ('Phreakish Eyes', 3, 16, 7, 6, 'Cogs & Gears; "A"');